In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([(1,2,3,4),(7,8,9,10)],dtype=int)

In [2]:
print(a)

[1 2 3]


In [3]:
print(b)

[[ 1  2  3  4]
 [ 7  8  9 10]]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
c=[1,2,3]
print(type(c))

<class 'list'>


In [8]:
d=np.array(c)
print(type(d))

<class 'numpy.ndarray'>


In [9]:
d.ndim

1

In [10]:
np.array([3])

array([3])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [19]:
np.random.rand(3,5)

array([[0.97238946, 0.90745571, 0.42706977, 0.49552766, 0.71250684],
       [0.18540013, 0.37178497, 0.01603508, 0.75182799, 0.11035845],
       [0.25139992, 0.02505883, 0.73278009, 0.19251362, 0.36802425]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.save("new_array",x)

NameError: name 'x' is not defined

In [23]:
x=[1,2,3]
np.save("new_array",x)

In [24]:
np.load("new_array.npy")

array([1, 2, 3])

In [28]:
np.loadtxt("New_file.npy")
# later

OSError: New_file.npy not found.

In [31]:
a1=[1,2,3]
b1=np.array(a1)
b1.size

3

In [32]:
b1.shape

(3,)

In [33]:
b1.dtype

dtype('int32')

In [34]:
np.copy(b1)

array([1, 2, 3])

In [39]:
b1.view(dtype="float32")

array([1.e-45, 3.e-45, 4.e-45], dtype=float32)

In [40]:
b1.view(dtype="int32")

array([1, 2, 3])

In [41]:
b2=np.array([9,6,8])
b2.sort()

In [43]:
print(b2)

[6 8 9]


In [55]:
b3=np.array([[3,1,2],[6,5,4]])
b3.sort(axis=0)
b3

array([[3, 1, 2],
       [6, 5, 4]])

In [56]:
b3.sort(axis=1)
b3

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b4=np.array([[3,1,12],[6,5,11]])
b4.sort(axis=0)
b4

array([[ 3,  1, 11],
       [ 6,  5, 12]])

In [58]:
b3.shape

(2, 3)

In [59]:
b3.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
b5=[1,2,3,4,5]
np.append(b5,6)

array([1, 2, 3, 4, 5, 6])

In [62]:
np.insert(b5,3,9)

array([1, 2, 3, 9, 4, 5])

In [64]:
np.delete(b4,1,axis=0)

array([[ 3,  1, 11]])

In [13]:
np.delete(b4,1,axis=1)

array([[ 3, 11],
       [ 6, 12]])

In [10]:
import numpy as np
b6=np.array([[1,2,3],[4,5,6]])
b7=np.array([[7,8,9],[10,11,12]])
np.concatenate((b6,b7),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
np.concatenate((b6,b7),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [14]:
b8=np.array([1,2,3,4,5,6])
np.split(b8,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [15]:
b8[0]=11

In [16]:
print(b8)

[11  2  3  4  5  6]


In [19]:
b6[1,2]=25
print(b6)

[[ 1  2  3]
 [ 4  5 25]]


In [20]:
b8[2]

3

In [22]:
b6[1,1]

5

In [23]:
b8[0:4]

array([11,  2,  3,  4])

In [32]:
b6[0:2,2]

array([ 3, 25])

In [33]:
b8[:2]

array([11,  2])

In [34]:
b6[:,1]

array([2, 5])

In [35]:
np.add(b6,b7)

array([[ 8, 10, 12],
       [14, 16, 37]])

In [36]:
np.subtract(b6,b7)

array([[-6, -6, -6],
       [-6, -6, 13]])

In [37]:
np.multiply(b6,b7)

array([[  7,  16,  27],
       [ 40,  55, 300]])

In [38]:
np.divide(b6,b7)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 2.08333333]])

In [39]:
np.exp(b6)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 7.20048993e+10]])

In [40]:
np.sqrt(b7)

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [41]:
b6==b7

array([[False, False, False],
       [False, False, False]])

In [42]:
np.array_equal(b6,b7)

False

In [43]:
b6.sum()

40

In [44]:
b6.min()

1

In [45]:
b6.max(axis=0)

array([ 4,  5, 25])

In [46]:
b6.max(axis=1)

array([ 3, 25])

In [47]:
b6.mean()

6.666666666666667

In [48]:
b6.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'