In [1]:
import numpy as np
print("Hello my world")

Hello my world


In [2]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
#horizontal stack
c=np.hstack(a)
c

array([1, 2, 3, 4, 5, 6])

In [11]:
#vertical stack
d=np.vstack(a)
d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
e=np.vstack((a,b))
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
#range
f=np.arange(1,11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Arange with step
g=np.arange(2,21,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
#table of 13
h=np.arange(13,131,13)
h

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [16]:
#divide 1 to 5 in 10 part
i=np.linspace(1.0,5.0,num=10)
i

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
a[0:1]

array([[1, 2, 3]])

In [18]:
a[0]

array([1, 2, 3])

In [19]:
a[1:2]

array([[4, 5, 6]])

In [20]:
#first array show
a[0]

array([1, 2, 3])

In [21]:
#second array show
a[1]

array([4, 5, 6])

In [22]:
a[1,0:]

array([4, 5, 6])

In [23]:
a[:,2]

array([3, 6])

In [24]:
#find second array in last element
a[1:2,2]

array([6])

In [25]:
#find first array in last element
a[0:1,2]

array([3])

In [26]:
j=np.ones((4,4))
j

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
k=np.random.randint(0,10,size=(3,2))
k

array([[4, 2],
       [0, 0],
       [2, 5]])

In [28]:
l=np.eye(3)
l

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#5 add in each element in array(broadcasting)
m=np.array([1,2,3,4,5])
m+=5
print(m)

[ 6  7  8  9 10]


In [30]:
n=np.random.randint(0,10,size=(3,3))
print(n)
print(n.max())

[[5 9 8]
 [4 5 9]
 [0 4 5]]
9


In [31]:
p=np.random.randint(0,10,size=(3,3))
print(p)
print(p.sum())

[[5 9 7]
 [5 8 1]
 [4 9 3]]
51


In [32]:
q=np.random.randint(0,10,size=(3,3))
print(q)
print(q.min())

[[9 6 9]
 [8 7 1]
 [0 0 8]]
0


In [35]:
r=np.random.randint(0,10,size=(3,3))
print(r)
print(r.shape)
print("After reshape")
r=r.reshape(9,1)
print(r)

[[2 9 9]
 [2 6 2]
 [4 4 9]]
(3, 3)
After reshape
[[2]
 [9]
 [9]
 [2]
 [6]
 [2]
 [4]
 [4]
 [9]]


In [3]:
import numpy as np
s=np.array([[1,2,3],[4,5,6]])
t=np.array([[7,8,9],[10,11,12]])
u=np.add(s,t)
u

array([[ 8, 10, 12],
       [14, 16, 18]])

In [5]:
v=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(v)
print("after swap")
v=v.T
print(v)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
after swap
[[10 40 70]
 [20 50 80]
 [30 60 90]]
