In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\Dell\Downloads\titanic.csv")
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
5            897         0       3   
6            898         1       3   
7            899         0       2   
8            900         1       3   
9            901         0       3   
10           902         0       3   
11           903         0       1   
12           904         1       1   
13           905         0       2   
14           906         1       1   
15           907         1       2   
16           908         0       2   
17           909         0       3   
18           910         1       3   
19           911         1       3   
20           912         0       1   
21           913         0       3   
22           914         1       1   
23           915         0       1   
24           916         1       1   
25           917         0       3   
26           918         1       1   
27           919         0       3   
28           920         0       1   
29           921         0       3   
..           ...       ...     ...   
388         1280         0       3   
389         1281         0       3   
390         1282         0       1   
391         1283         1       1   
392         1284         0       3   
393         1285         0       2   
394         1286         0       3   
395         1287         1       1   
396         1288         0       3   
397         1289         1       1   
398         1290         0       3   
399         1291         0       3   
400         1292         1       1   
401         1293         0       2   
402         1294         1       1   
403         1295         0       1   
404         1296         0       1   
405         1297         0       2   
406         1298         0       2   
407         1299         0       1   
408         1300         1       3   
409         1301         1       3   
410         1302         1       3   
411         1303         1       1   
412         1304         1       3   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                                  Name     Sex   Age  SibSp  \
0                                     Kelly, Mr. James    male  34.5      0   
1                     Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2                            Myles, Mr. Thomas Francis    male  62.0      0   
3                                     Wirz, Mr. Albert    male  27.0      0   
4         Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1   
5                           Svensson, Mr. Johan Cervin    male  14.0      0   
6                                 Connolly, Miss. Kate  female  30.0      0   
7                         Caldwell, Mr. Albert Francis    male  26.0      1   
8            Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0   
9                              Davies, Mr. John Samuel    male  21.0      2   
10                                    Ilieff, Mr. Ylio    male   NaN      0   
11                          Jones, Mr. Charles Cresson    male  46.0      0   
12       Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female  23.0      1   
13                                Howard, Mr. Benjamin    male  63.0      1   
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...  female  47.0      1   
15       del Carlo, Mrs. Sebastiano (Argenia Genovesi)  female  24.0      1   
16                                   Keane, Mr. Daniel    male  35.0      0   
17                                   Assaf, Mr. Gerios    male  21.0      0   
18                        Ilmakangas, Miss. Ida Livija  female  27.0      1   
19               Assaf Khalil, Mrs. Mariana (Miriam")"  female  45.0

In [54]:
df1 = df[['Survived','Pclass','SibSp','Parch','Embarked']]
df1

Survived  Pclass  SibSp  Parch Embarked
0           0       3      0      0        Q
1           1       3      1      0        S
2           0       2      0      0        Q
3           0       3      0      0        S
4           1       3      1      1        S
5           0       3      0      0        S
6           1       3      0      0        Q
7           0       2      1      1        S
8           1       3      0      0        C
9           0       3      2      0        S
10          0       3      0      0        S
11          0       1      0      0        S
12          1       1      1      0        S
13          0       2      1      0        S
14          1       1      1      0        S
15          1       2      1      0        C
16          0       2      0      0        Q
17          0       3      0      0        C
18          1       3      1      0        S
19          1       3      0      0        C
20          0       1      1      0        C
21          0       3      0      1        S
22          1       1      0      0        S
23          0       1      0      1        C
24          1       1      1      3        C
25          0       3      1      0        S
26          1       1      0      1        C
27          0       3      0      0        C
28          0       1      0      0        S
29          0       3      2      0        C
..        ...     ...    ...    ...      ...
388         0       3      0      0        Q
389         0       3      3      1        S
390         0       1      0      0        S
391         1       1      0      1        S
392         0       3      0      2        S
393         0       2      0      0        S
394         0       3      3      1        S
395         1       1      1      0        S
396         0       3      0      0        Q
397         1       1      1      1        C
398         0       3      0      0        S
399         0       3      0      0        Q
400         1       1      0      0        S
401         0       2      1      0        S
402         1       1      0      1        C
403         0       1      0      0        S
404         0       1      1      0        C
405         0       2      0      0        C
406         0       2      1      0        S
407         0       1      1      1        C
408         1       3      0      0        Q
409         1       3      1      1        S
410         1       3      0      0        Q
411         1       1      1      0        Q
412         1       3      0      0        S
413         0       3      0      0        S
414         1       1      0      0        C
415         0       3      0      0        S
416         0       3      0      0        S
417         0       3      1      1        C

[418 rows x 5 columns]

In [56]:
x=df1.iloc[:,:4].values
x

array([[0, 3, 0, 0],
       [1, 3, 1, 0],
       [0, 2, 0, 0],
       ...,
       [0, 3, 0, 0],
       [0, 3, 0, 0],
       [0, 3, 1, 1]], dtype=int64)

In [57]:
y=df1.iloc[:,4].values
y

array(['Q', 'S', 'Q', 'S', 'S', 'S', 'Q', 'S', 'C', 'S', 'S', 'S', 'S',
       'S', 'S', 'C', 'Q', 'C', 'S', 'C', 'C', 'S', 'S', 'C', 'C', 'S',
       'C', 'C', 'S', 'C', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S',
       'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C', 'Q', 'C', 'S', 'S', 'C',
       'S', 'S', 'C', 'Q', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'Q', 'C',
       'S', 'Q', 'S', 'C', 'S', 'Q', 'S', 'S', 'C', 'C', 'C', 'S', 'S',
       'S', 'Q', 'C', 'S', 'S', 'S', 'Q', 'C', 'Q', 'S', 'Q', 'S', 'S',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'Q', 'S',
       'C', 'S', 'Q', 'Q', 'S', 'S', 'C', 'Q', 'C', 'Q', 'S', 'C', 'C',
       'S', 'C', 'S', 'S', 'Q', 'C', 'S', 'Q', 'S', 'S', 'Q', 'S', 'S',
       'S', 'C', 'S', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'Q', 'C', 'S', 'S', 'S', 'S', 'C', 'S', 'C',
       'S', 'S', 'C', 'S', 'C', 'S', 'S', 'S', 'C', 'S', 'C', 'S

In [58]:
from sklearn.preprocessing import LabelEncoder

In [59]:
labelencoder_y=LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 0, 2,
       2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2,
       1, 2, 0, 2, 1, 2, 2, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 2, 1, 0, 1, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 2,
       0, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2,
       2, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2,
       0, 2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 0, 2,
       0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2,
       2, 2, 0, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 2, 2,

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [62]:
x_train.size

1168

In [63]:
x_test.size

504

In [64]:
y_train.size

292

In [65]:
y_test.size

126

In [66]:
from sklearn.linear_model import LogisticRegression

In [67]:
logmodel = LogisticRegression()

In [68]:
logmodel.fit(x_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [69]:
y_pred = logmodel.predict(x_test)
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [70]:
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [71]:
from sklearn.metrics import confusion_matrix

In [72]:
confusion_matrix(y_test,y_pred)

array([[ 4,  0, 29],
       [ 0,  0, 19],
       [ 2,  0, 72]], dtype=int64)

In [73]:
logmodel.score(x_test,y_test)

0.6031746031746031

In [74]:
from sklearn.neighbors import KNeighborsClassifier

In [75]:
classifier_knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)

In [76]:
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [78]:
y_pred_knn = classifier_knn.predict(x_test)

In [79]:
y_pred_knn

array([2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 0,
       2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2,
       2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [80]:
from sklearn.metrics import confusion_matrix

In [81]:
confusion_matrix(y_test,y_pred_knn)

array([[12,  0, 21],
       [ 0,  0, 19],
       [16,  0, 58]], dtype=int64)

In [82]:
classifier_knn.score(x_test,y_test)

0.5555555555555556

In [83]:
from sklearn.metrics import accuracy_score

In [84]:
accuracy_score(y_pred_knn,y_test)

0.5555555555555556

In [85]:
from sklearn.naive_bayes import GaussianNB

In [86]:
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [87]:
y_pred_nb = classifier_nb.predict(x_test)

In [88]:
y_pred_nb

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2,
       1, 2, 0, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       2, 1, 1, 0, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1])

In [89]:
from sklearn.metrics import accuracy_score

In [92]:
accuracy_score(y_pred_knn,y_test)

0.5555555555555556

In [93]:
confusion_matrix(y_test,y_pred_knn)

array([[12,  0, 21],
       [ 0,  0, 19],
       [16,  0, 58]], dtype=int64)

In [94]:
classifier_nb.score(x_test,y_test)

0.30158730158730157