In [1]:
import cv2

In [2]:
img=cv2.imread("a.png")
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
img=cv2.imread("a.png")
img1=cv2.resize(img,(400,600))
cv2.imshow("image",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img=cv2.imread("a.png",0)
print(img)
print(img.shape)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(218, 490)


In [8]:
import numpy as np

In [9]:
matx=np.zeros((200,200))
matx

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
cv2.imshow("aaaa",matx)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
img=cv2.imread("a.png")
img1=cv2.resize(img,(600,600))
i=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
cv2.imshow("image",i)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
img=cv2.imread("a.png")
img1=cv2.resize(img,(600,600))
i=cv2.cvtColor(img1,cv2.COLOR_BGR2YUV)
cv2.imshow("image",i)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
img=cv2.imread("a.png")
img1=cv2.resize(img,(600,600))
i=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
icopy=np.copy(i)
icopy[icopy[:,:]<100]=0
cv2.imshow("image",icopy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
img=cv2.imread("a.png")
icopy=np.copy(img)
icopy[(icopy[:,:,0]>100) | (icopy[:,:,1]>200) | (icopy[:,:,2]>200)]=255
cv2.imshow("image",icopy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import cv2
import numpy as np

In [2]:
img=cv2.imread("a.png")
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
img=cv2.imread("a.png",0)
print(img)
print(img.shape)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(218, 490)


In [11]:
img=cv2.imread("a.png")
icopy=np.copy(img)
icopy[(icopy[:,:,0]<100) | (icopy[:,:,1]>200) | (icopy[:,:,2]>200)]=255
cv2.imshow("image",icopy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
img=cv2.imread("a.png")
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
img=cv2.imread("a.png",0)
print(img)
print(img.shape)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(218, 490)


In [15]:
img=cv2.imread("a.png")
img1=cv2.resize(img,(600,600))
i=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
cv2.imshow("image",i)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
img=cv2.imread("a.png")
icopy=np.copy(img)
icopy[(icopy[:,:,0]<100) | (icopy[:,:,1]>200) | (icopy[:,:,2]>200)]=255
cv2.imshow("image",icopy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
img=cv2.imread("a.png")
icopy=np.copy(img)
icopy[(icopy[:,:,0]>100) | (icopy[:,:,1]>200) | (icopy[:,:,2]>200)]=255
cv2.imshow("image",icopy)
cv2.waitKey(0)
cv2.destroyAllWindows()