In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv(r'D:\dhrumit\sem2\MLP\cars.csv')

In [10]:
df

Unnamed: 0  price      brand     model  year   title_status  mileage  \
0             0   6300     toyota   cruiser  2008  clean vehicle   274117   
1             1   2899       ford        se  2011  clean vehicle   190552   
2             2   5350      dodge       mpv  2018  clean vehicle    39590   
3             3  25000       ford      door  2014  clean vehicle    64146   
4             4  27700  chevrolet      1500  2018  clean vehicle     6654   
5             5   5700      dodge       mpv  2018  clean vehicle    45561   
6             6   7300  chevrolet        pk  2010  clean vehicle   149050   
7             7  13350        gmc      door  2017  clean vehicle    23525   
8             8  14600  chevrolet    malibu  2018  clean vehicle     9371   
9             9   5250       ford       mpv  2017  clean vehicle    63418   
10           10  10400      dodge     coupe  2009  clean vehicle   107856   
11           11  12920        gmc       mpv  2017  clean vehicle    39650   
12           12  31900  chevrolet      1500  2018  clean vehicle    22909   
13           13   5430   chrysler     wagon  2017  clean vehicle   138650   
14           14  20700       ford      door  2013  clean vehicle   100757   
15           15  12710        gmc      door  2017  clean vehicle    25747   
16           16   5200        kia     forte  2018  clean vehicle    46194   
17           17  16500      buick    encore  2018  clean vehicle    20002   
18           18   5210       ford       mpv  2017  clean vehicle    35714   
19           19  38100       ford      door  2013  clean vehicle    54380   
20           20  12520        gmc      door  2017  clean vehicle    30114   
21           21   7300        kia     forte  2018  clean vehicle    38823   
22           22  15000  chevrolet      door  2015  clean vehicle    61578   
23           23   6180       ford       mpv  2017  clean vehicle    46010   
24           24  20800       ford      door  2013  clean vehicle   105510   
25           25  11900        gmc      door  2017  clean vehicle    28040   
26           26  21500        kia   sorento  2020  clean vehicle    11451   
27           27  12000      buick      door  2014  clean vehicle    31039   
28           28   4190       ford     doors  2017  clean vehicle    44174   
29           29  13000       ford   chassis  2008  clean vehicle    93698   
..          ...    ...        ...       ...   ...            ...      ...   
147         147  33300   cadillac       esv  2015  clean vehicle    57932   
148         148  10780      dodge       mpv  2018  clean vehicle    19420   
149         149   6700       ford   cutaway  2014  clean vehicle   204155   
150         150  20000  chevrolet      1500  2016  clean vehicle    93493   
151         151   6440   chrysler     doors  2018  clean vehicle    20942   
152         152  19900       ford      door  2016  clean vehicle    86826   
153         153  37000  chevrolet      door  2015  clean vehicle    45787   
154         154   4040      dodge       mpv  2018  clean vehicle    50765   
155         155  22300       ford  explorer  2016  clean vehicle    62774   
156         156  31200  chevrolet      door  2011  clean vehicle    76326   
157         157   4290      dodge       mpv  2018  clean vehicle    39029   
158         158  22800       ford        el  2016  clean vehicle    72885   
159         159  19002   cadillac      door  2016  clean vehicle    46467   
160         160   4160      dodge       mpv  2018  clean vehicle     6743   
161         161  18500       ford      edge  2016  clean vehicle    33514   
162         162  39000        bmw    series  2016  clean vehicle    39917   
163         163   6060      dodge     doors  2018  clean vehicle    32504   
164         164  28800       ford      door  2016  clean vehicle    77638   
165         165  40000        bmw    series  2016  clean vehicle    31727   
166         166   6140      dodge     doors  2018  clean vehicle    52966   
1

In [15]:
df1 = df[['brand','model','year','mileage','color','condition','price']]
df1

brand     model  year  mileage   color      condition  price
0       toyota   cruiser  2008   274117   black   10 days left   6300
1         ford        se  2011   190552  silver    6 days left   2899
2        dodge       mpv  2018    39590  silver    2 days left   5350
3         ford      door  2014    64146    blue  22 hours left  25000
4    chevrolet      1500  2018     6654     red  22 hours left  27700
5        dodge       mpv  2018    45561   white    2 days left   5700
6    chevrolet        pk  2010   149050   black  22 hours left   7300
7          gmc      door  2017    23525    gray  20 hours left  13350
8    chevrolet    malibu  2018     9371  silver  22 hours left  14600
9         ford       mpv  2017    63418   black    2 days left   5250
10       dodge     coupe  2009   107856  orange  22 hours left  10400
11         gmc       mpv  2017    39650   white  20 hours left  12920
12   chevrolet      1500  2018    22909   black  22 hours left  31900
13    chrysler     wagon  2017   138650    gray    2 days left   5430
14        ford      door  2013   100757   black  22 hours left  20700
15         gmc      door  2017    25747   white  20 hours left  12710
16         kia     forte  2018    46194    blue    2 days left   5200
17       buick    encore  2018    20002     red  22 hours left  16500
18        ford       mpv  2017    35714   white    2 days left   5210
19        ford      door  2013    54380    gray  22 hours left  38100
20         gmc      door  2017    30114   white  20 hours left  12520
21         kia     forte  2018    38823   black    2 days left   7300
22   chevrolet      door  2015    61578   black    2 days left  15000
23        ford       mpv  2017    46010    blue    2 days left   6180
24        ford      door  2013   105510  silver  22 hours left  20800
25         gmc      door  2017    28040  silver  20 hours left  11900
26         kia   sorento  2020    11451    blue    2 days left  21500
27       buick      door  2014    31039   brown    2 days left  12000
28        ford     doors  2017    44174   white    2 days left   4190
29        ford   chassis  2008    93698   white  22 hours left  13000
..         ...       ...   ...      ...     ...            ...    ...
147   cadillac       esv  2015    57932    gray  21 hours left  33300
148      dodge       mpv  2018    19420   white  16 hours left  10780
149       ford   cutaway  2014   204155   beige    3 days left   6700
150  chevrolet      1500  2016    93493   white  21 hours left  20000
151   chrysler     doors  2018    20942    gray  17 hours left   6440
152       ford      door  2016    86826    gray  21 hours left  19900
153  chevrolet      door  2015    45787   white  21 hours left  37000
154      dodge       mpv  2018    50765     red  16 hours left   4040
155       ford  explorer  2016    62774   black  21 hours left  22300
156  chevrolet      door  2011    76326    gray  21 hours left  31200
157      dodge       mpv  2018    39029   white  16 hours left   4290
158       ford        el  2016    72885  silver  21 hours left  22800
159   cadillac      door  2016    46467   white  20 hours left  19002
160      dodge       mpv  2018     6743    gray  16 hours left   4160
161       ford      edge  2016    33514   white  21 hours left  18500
162        bmw    series  2016    39917    blue    2 days left  39000
163      dodge     doors  2018    32504   black  18 hours left   6060
164       ford      door  2016    77638   white  21 hours left  28800
165        bmw    series  2016    31727    gray    2 days left  40000
166      dodge     doors  2018    52966  silver  16 hours left   6140
167       ford      flex  2016    24157    gray  21 hours left  21000
168      buick      door  2016    51393   beige  20 hours left  20105
169      dodge     doors  2018    35461   white  16 hours left   6760
170       ford      door  2014    47055   brown    1 days left  25800
171        bmw    series  2016    33110   black    2 days left  39000
172      dodge     

In [18]:
x= df1.iloc[:,:6]

In [20]:
y=df1.iloc[:,6]

In [21]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le = LabelEncoder()

In [33]:
x['brand'] = le.fit_transform(x['brand'])

In [34]:
x['model'] = le.fit_transform(x['model'])

In [35]:
x['year'] = le.fit_transform(x['year'])

In [36]:
x['mileage'] = le.fit_transform(x['mileage'])

In [37]:
x['color'] = le.fit_transform(x['color'])

In [67]:
x['condition'] = le.fit_transform(x['condition'])
x

brand  model  year  mileage  color  condition  price
0       12     14     2      175      1          1     26
1        6     38     5      173     10         14      1
2        5     34    11      102     10          6     16
3        6     17     7      148      2         10    112
4        3      0    11        3      9         10    121
5        5     34    11      119     12          6     21
6        3     36     4      170      1         10     38
7        7     17    10       26      6          8     60
8        3     33    11        5     10         10     64
9        6     34    10      147      1          6     14
10       5     13     3      164      8         10     48
11       7     34    10      103     12          8     57
12       3      0    11       24      1         10    131
13       4     44    10      169      6          6     17
14       6     17     6      162      1         10     94
15       7     17    10       34     12          8     55
16      10     31    11      123      2          6     12
17       1     23    11       20      9         10     72
18       6     34    10       87     12          6     13
19       6     17     6      139      6         10    138
20       7     17    10       52     12          8     54
21      10     31    11       97      1          6     38
22       3     17     8      145      1          6     66
23       6     34    10      121      2          6     25
24       6     17     6      163     10         10     95
25       7     17    10       40     10          8     52
26      10     40    13        6      2          6     99
27       1     17     7       57      3          6     53
28       6     18    10      115     12          6      5
29       6      8     2      160     12         10     58
..     ...    ...   ...      ...    ...        ...    ...
147      2     26     8      142      6          9    134
148      5     34    11       18     12          2     49
149      6     15     7      174      0         11     30
150      3      0     9      159     12          9     92
151      4     18    11       21      6          3     28
152      6     17     9      157      6          9     91
153      3     17     8      120     12          9    137
154      5     34    11      134      9          2      2
155      6     27     9      146      1          9    100
156      3     17     5      152      6          9    129
157      5     34    11       99     12          2      7
158      6     21     9      150     10          9    101
159      2     17     9      125     12          8     84
160      5     34    11        4      6          2      4
161      6     20     9       76     12          9     81
162      0     39     9      107      2          6    139
163      5     18    11       71      1          4     23
164      6     17     9      153     12          9    124
165      0     39     9       62      6          6    141
166      5     18    11      138     10          2     24
167      6     29     9       28      6          9     97
168      1     17     9      136      0          8     93
169      5     18    11       84     12          2     31
170      6     17     7      128      3          0    114
171      0     39     9       73      1          6    139
172      5     34    11      105      1          2     18
173      6     17     7      151      1          9     64
174      3      0     9       77      1          8    110
175      6     17    10      111     12          6     67
176      6     17     7      154     12          9     42

[177 rows x 7 columns]

In [40]:
y = le.fit_transform(y)

In [41]:
y

array([ 26,   1,  16, 112, 121,  21,  38,  60,  64,  14,  48,  57, 131,
        17,  94,  55,  12,  72,  13, 138,  54,  38,  66,  25,  95,  52,
        99,  53,   5,  58,  55,  81, 127,  15,  58,  52,  73,  85,  39,
        35,  55,  73, 128,  27, 146,  54,  71,  83,  19, 145,  55,  70,
       120,  41,  90,  57,  92,  79, 102,  81,  61,  94,  75,  29, 125,
        55,  98,  82,   8,  86,  56,  68, 126,   9,  87,  54,  69, 116,
         3,  80,  54,  76,  80,  10, 107,  59,  77,  65,   3,  51,  45,
        40, 109,  47, 140, 144,  67, 135, 119,  22,  62, 106,  49,  63,
       113,  36,  44,  78,  43, 103, 109,  35,  74, 136,  34, 112,  96,
        46, 118, 111,  36, 123, 142, 104, 105,  50, 133, 143,  33,  52,
       117,   4,  88,  20, 115, 108,  11,  89, 132,  32,   6,   0, 130,
        37,   0, 122,  32, 134,  49,  30,  92,  28,  91, 137,   2, 100,
       129,   7, 101,  84,   4,  81, 139,  23, 124, 141,  24,  97,  93,
        31, 114, 139,  18,  64, 110,  67,  42], dtype=int64)

In [42]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [55]:
x_train.shape

(123, 7)

In [56]:
y_train.shape

(123,)

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
lin_model = LogisticRegression()

In [59]:
lin_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [60]:
lin_model.fit(x_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [63]:
y_pred = lin_model.predict(x_test)
y_pred

array([ 55, 100,  49,  48,  49,  55,  53, 138,  52,  88, 139,  80,  51,
        54,  55,   0, 118,  55,  55,  77,  16, 139,  55,  92,  14,  92,
        47,  25, 131,  48,  24,  64,  55, 112,  55,  92, 137,  65, 134,
       109,  24,  64,  84,  40, 132,  87, 116,  52,   6,  14, 125,  42,
       140, 105], dtype=int64)

In [64]:
y_test

array([ 52, 104,  35,  58,  36,  57,  75, 145,  46,  82, 141,  81,  43,
        56,  55,   1, 146, 112,  63,  98,  19, 144,   8,  26,  18,  69,
        50,  22, 143,  58,  32,  74,  35, 107,  97,  52, 109,  85, 129,
       113,  31,  38,  79,  66, 136, 128, 130,  54,  11,  17, 133,   5,
       121,  93], dtype=int64)

In [65]:
lin_model.score(x_test,y_test)

0.018518518518518517

In [69]:
lin_model.predict([[5,10,20,10,5,6,8]])

array([28], dtype=int64)