In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

In [6]:
a = [1,2,3,4,5]
type(a)

list

In [8]:
arr1 = np.array(a)
type(arr1)

numpy.ndarray

In [11]:
arr2 = np.array([[10,5,8],[15,20,18]])
arr2.ndim

2

In [16]:
arr1.size

5

In [17]:
arr2.size

6

In [19]:
arr1.shape

(5,)

In [20]:
arr2.shape

(2, 3)

In [21]:
arr1.dtype

dtype('int32')

In [24]:
arr3 = np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr5 = np.arange(1,10,2) # 2 is a gap
arr5

array([1, 3, 5, 7, 9])

In [32]:
arr6 = np.linspace(1,10,5)  # 5 n a number of element
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
arr7 = np.random.random((3,3))
arr7

array([[0.79805963, 0.51074604, 0.52654989],
       [0.61530217, 0.01793313, 0.18312139],
       [0.77781491, 0.92945778, 0.39963005]])

In [42]:
arr8 = np.random.randint(0,100,(3,3))
arr8

array([[83, 72, 17],
       [72, 27,  8],
       [44, 15, 59]])

In [43]:
arr9 = np.random.rand(3,3)
arr9

array([[0.10083324, 0.97029546, 0.05251225],
       [0.64382147, 0.60329275, 0.87645419],
       [0.11433275, 0.35394654, 0.72538243]])

In [52]:
arr1.reshape(5,-1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [53]:
arr2.shape

(2, 3)

In [54]:
arr2.reshape(3,2)

array([[10,  5],
       [ 8, 15],
       [20, 18]])

In [57]:
np.hstack(arr1)

array([1, 2, 3, 4, 5])

In [58]:
np.vstack(arr1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [59]:
np.hstack(arr2)

array([10,  5,  8, 15, 20, 18])

In [61]:
arr10 = np.full((3,2),5)
arr10

array([[5, 5],
       [5, 5],
       [5, 5]])

In [63]:
arr11 = np.eye(4)
arr11

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
arr2.sort
arr2

array([[ 5,  8, 10],
       [15, 18, 20]])

In [71]:
df = pd.read_csv('iris.csv')
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [73]:
x = df.iloc[:,:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [75]:
y = df.iloc[:,4].values
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [76]:
from sklearn.preprocessing import LabelEncoder

In [77]:
lb = LabelEncoder()

In [78]:
y = lb.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
lr = LogisticRegression()

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [84]:
lr.fit(x_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [86]:
y_pread = lr.predict(x_test)
y_pread

array([2, 1, 1, 2, 0, 1, 2, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 0, 1, 1, 0, 1,
       1, 2, 2, 2, 2, 2, 1, 0, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 0, 2, 0, 1,
       2])

In [87]:
lr.score(x_test,y_test)

0.9333333333333333

In [89]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pread)

array([[ 7,  0,  0],
       [ 0, 14,  2],
       [ 0,  1, 21]], dtype=int64)

In [90]:
from sklearn.metrics import accuracy_score

In [91]:
accuracy_score(y_test,y_pread)

0.9333333333333333

In [92]:
from sklearn.neighbors import KNeighborsClassifier

In [101]:
knn = KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)

In [102]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [103]:
y_kn_pred = knn.predict(x_test)
y_kn_pred

array([2, 1, 1, 2, 0, 1, 2, 0, 1, 2, 2, 1, 1, 2, 2, 2, 2, 0, 1, 1, 0, 1,
       2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 0, 2, 0, 1,
       2])

In [104]:
knn.score(x_test,y_test)

0.9777777777777777

In [105]:
from sklearn.metrics import accuracy_score

In [106]:
accuracy_score(y_test,y_kn_pred)

0.9777777777777777

In [107]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_kn_pred,y_test)

array([[ 7,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 21]], dtype=int64)

In [108]:
from sklearn.naive_bayes import GaussianNB

In [109]:
nb = GaussianNB()

In [110]:
nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [111]:
y_nb_pred = nb.predict(x_test)
y_nb_pred

array([2, 1, 1, 2, 0, 1, 2, 0, 1, 2, 2, 1, 1, 2, 2, 2, 2, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 0, 2, 0, 1,
       2])

In [112]:
nb.score(x_test,y_test)

0.9777777777777777

In [113]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_kn_pred,y_test)

array([[ 7,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 21]], dtype=int64)