In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('pokemon_data.csv')
df

#                       Name    Type 1  Type 2   HP  Attack  Defense  \
0      1                  Bulbasaur     Grass  Poison   45      49       49   
1      2                    Ivysaur     Grass  Poison   60      62       63   
2      3                   Venusaur     Grass  Poison   80      82       83   
3      3      VenusaurMega Venusaur     Grass  Poison   80     100      123   
4      4                 Charmander      Fire     NaN   39      52       43   
5      5                 Charmeleon      Fire     NaN   58      64       58   
6      6                  Charizard      Fire  Flying   78      84       78   
7      6  CharizardMega Charizard X      Fire  Dragon   78     130      111   
8      6  CharizardMega Charizard Y      Fire  Flying   78     104       78   
9      7                   Squirtle     Water     NaN   44      48       65   
10     8                  Wartortle     Water     NaN   59      63       80   
11     9                  Blastoise     Water     NaN   79      83      100   
12     9    BlastoiseMega Blastoise     Water     NaN   79     103      120   
13    10                   Caterpie       Bug     NaN   45      30       35   
14    11                    Metapod       Bug     NaN   50      20       55   
15    12                 Butterfree       Bug  Flying   60      45       50   
16    13                     Weedle       Bug  Poison   40      35       30   
17    14                     Kakuna       Bug  Poison   45      25       50   
18    15                   Beedrill       Bug  Poison   65      90       40   
19    15      BeedrillMega Beedrill       Bug  Poison   65     150       40   
20    16                     Pidgey    Normal  Flying   40      45       40   
21    17                  Pidgeotto    Normal  Flying   63      60       55   
22    18                    Pidgeot    Normal  Flying   83      80       75   
23    18        PidgeotMega Pidgeot    Normal  Flying   83      80       80   
24    19                    Rattata    Normal     NaN   30      56       35   
25    20                   Raticate    Normal     NaN   55      81       60   
26    21                    Spearow    Normal  Flying   40      60       30   
27    22                     Fearow    Normal  Flying   65      90       65   
28    23                      Ekans    Poison     NaN   35      60       44   
29    24                      Arbok    Poison     NaN   60      85       69   
..   ...                        ...       ...     ...  ...     ...      ...   
770  700                    Sylveon     Fairy     NaN   95      65       65   
771  701                   Hawlucha  Fighting  Flying   78      92       75   
772  702                    Dedenne  Electric   Fairy   67      58       57   
773  703                    Carbink      Rock   Fairy   50      50      150   
774  704                      Goomy    Dragon     NaN   45      50       35   
775  705                    Sliggoo    Dragon     NaN   68      75       53   
776  706                     Goodra    Dragon     NaN   90     100       70   
777  707                     Klefki     Steel   Fairy   57      80       91   
778  708                   Phantump     Ghost   Grass   43      70       48   
779  709                  Trevenant     Ghost   Grass   85     110       76   
780  710      PumpkabooAverage Size     Ghost   Grass   49      66       70   
781  710        PumpkabooSmall Size     Ghost   Grass   44      66       70   
782  710        PumpkabooLarge Size     Ghost   Grass   54      66       70   
783  710        PumpkabooSuper Size     Ghost   Grass   59      66       70   
784  711      GourgeistAverage Size     Ghost   Grass   65      90      122   
785  711        GourgeistSmall Size     Ghost   Grass   55      85      122   
786  711        GourgeistLarge Size     Ghost   Grass   75      95      122   
787  711        GourgeistSuper Size     Ghost   Grass   85     100      122   
788  712                   Bergmite       Ice     NaN   5

In [7]:
x = df.iloc[:,4:11]
x

HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0     45      49       49       65       65     45           1
1     60      62       63       80       80     60           1
2     80      82       83      100      100     80           1
3     80     100      123      122      120     80           1
4     39      52       43       60       50     65           1
5     58      64       58       80       65     80           1
6     78      84       78      109       85    100           1
7     78     130      111      130       85    100           1
8     78     104       78      159      115    100           1
9     44      48       65       50       64     43           1
10    59      63       80       65       80     58           1
11    79      83      100       85      105     78           1
12    79     103      120      135      115     78           1
13    45      30       35       20       20     45           1
14    50      20       55       25       25     30           1
15    60      45       50       90       80     70           1
16    40      35       30       20       20     50           1
17    45      25       50       25       25     35           1
18    65      90       40       45       80     75           1
19    65     150       40       15       80    145           1
20    40      45       40       35       35     56           1
21    63      60       55       50       50     71           1
22    83      80       75       70       70    101           1
23    83      80       80      135       80    121           1
24    30      56       35       25       35     72           1
25    55      81       60       50       70     97           1
26    40      60       30       31       31     70           1
27    65      90       65       61       61    100           1
28    35      60       44       40       54     55           1
29    60      85       69       65       79     80           1
..   ...     ...      ...      ...      ...    ...         ...
770   95      65       65      110      130     60           6
771   78      92       75       74       63    118           6
772   67      58       57       81       67    101           6
773   50      50      150       50      150     50           6
774   45      50       35       55       75     40           6
775   68      75       53       83      113     60           6
776   90     100       70      110      150     80           6
777   57      80       91       80       87     75           6
778   43      70       48       50       60     38           6
779   85     110       76       65       82     56           6
780   49      66       70       44       55     51           6
781   44      66       70       44       55     56           6
782   54      66       70       44       55     46           6
783   59      66       70       44       55     41           6
784   65      90      122       58       75     84           6
785   55      85      122       58       75     99           6
786   75      95      122       58       75     69           6
787   85     100      122       58       75     54           6
788   55      69       85       32       35     28           6
789   95     117      184       44       46     28           6
790   40      30       35       45       40     55           6
791   85      70       80       97       80    123           6
792  126     131       95      131       98     99           6
793  126     131       95      131       98     99           6
794  108     100      121       81       95     95           6
795   50     100      150      100      150     50           6
796   50     160      110      160      110    110           6
797   80     110       60      150      130     70           6
798   80     160       60      170      130     80           6
799   80     110      120      130       90     70           6

[800 rows x 7 columns]

In [8]:
y = df.iloc[:,11]
y

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
770    False
771    False
772    False
773    False
774    False
775    False
776    False
777    False
778    False
779    False
780    False
781    False
782    False
783    False
784    False
785    False
786    False
787    False
788    False
789    False
790    False
791    False
792     True
793     True
794     True
795     True
796     True
797     True
798     True
799     True
Name: Legendary, Length: 800, dtype: bool

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
labelencoder = LabelEncoder()

In [11]:
y = labelencoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [17]:
x_train.size

3920

In [18]:
x_test.size

1680

In [19]:
y_train.size

560

In [20]:
y_test.size

240

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
li_model = LogisticRegression()

In [23]:
li_model.fit(x_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
y_pred = li_model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [26]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
confusion_matrix(y_pred,y_test)

array([[218,  14],
       [  2,   6]], dtype=int64)

In [29]:
li_model.score(x_test,y_test)

0.9333333333333333

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.9333333333333333

In [32]:
from sklearn.svm import SVC

In [35]:
d = SVC(kernel = 'sigmoid')

In [36]:
d

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [37]:
d.fit(x_train,y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [38]:
y_pred_svc  = d.predict(x_test)

In [39]:
y_pred_svc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [40]:
confusion_matrix(y_pred,y_test)

array([[218,  14],
       [  2,   6]], dtype=int64)

In [41]:
d.score(x_test,y_test)

0.9166666666666666

In [44]:
from sklearn.neighbors import KNeighborsClassifier
sk_knn = KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)

In [45]:
sk_knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
sk_knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [49]:
y_pred_knn=sk_knn.predict(x_test)

In [48]:
confusion_matrix(y_test,y_pred_knn)


array([[218,   2],
       [ 14,   6]], dtype=int64)

In [51]:
sk_knn.score(x_test,y_test)

0.9541666666666667

In [52]:
from sklearn.naive_bayes import GaussianNB
sk_G = GaussianNB()

In [53]:
sk_G.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [54]:
y_pred_G = sk_G.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [55]:
sk_G.score(x_test,y_test)

0.9333333333333333