In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a.dtype

dtype('int32')

In [16]:
b=np.array([(1,2,3),(4,5,6)],dtype=float)

In [17]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
b.dtype

dtype('float64')

In [19]:
a.size

3

In [20]:
b.size

6

In [24]:
c=np.array([(1,2,3),(4,5,6),(7,8,9)])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
c.size

9

In [26]:
a.shape

(3,)

In [27]:
b.shape

(2, 3)

In [28]:
c.shape

(3, 3)

In [29]:
c.dtype

dtype('int32')

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
np.zeros((5,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
np.full((3,4),20)

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [36]:
np.random.rand(3,5)

array([[0.45525447, 0.57768021, 0.12131412, 0.459741  , 0.16584686],
       [0.08294895, 0.93442669, 0.39558539, 0.60362727, 0.46900291],
       [0.84787455, 0.06055162, 0.07321303, 0.19557094, 0.56116882]])

In [37]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
d=np.copy(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
e=np.array([80,60,70,90,12])
e

array([80, 60, 70, 90, 12])

In [45]:
f=np.array([[45,60,30],[15,30,20]])
f

array([[45, 60, 30],
       [15, 30, 20]])

In [46]:
g=np.array([[[120,110,115],[125,140,130],[180,190,170]]])
g

array([[[120, 110, 115],
        [125, 140, 130],
        [180, 190, 170]]])

In [48]:
g.shape

(1, 3, 3)

In [50]:
e.sort()
e

array([12, 60, 70, 80, 90])

In [65]:
f.sort()
f

array([[15, 20, 30],
       [30, 45, 60]])

In [62]:
f.sort(axis=0)
f

array([[15, 20, 30],
       [30, 45, 60]])

In [53]:
f.sort(axis=1)
f

array([[15, 20, 30],
       [30, 45, 60]])

In [67]:
g.sort()
g

array([[[110, 115, 120],
        [125, 130, 140],
        [170, 180, 190]]])

In [57]:
g.sort(axis=0)
g

array([[[110, 115, 120],
        [125, 130, 140],
        [170, 180, 190]]])

In [70]:
f1=f.reshape(3,2)
f1

array([[15, 20],
       [30, 30],
       [45, 60]])

In [73]:
e1=np.append(e,7)
e1

array([12, 60, 70, 80, 90,  7])

In [75]:
e2=np.delete(e,1)
e2

array([12, 70, 80, 90])

In [91]:
f1=f.view(dtype="int")
f1

array([[15, 20, 30],
       [30, 45, 60]])

In [93]:
h=np.array([[1,2,3],[4,5,6]])
i=np.array([[7,8,9],[10,11,12]])
i

array([[ 7,  8,  9],
       [10, 11, 12]])

In [96]:
j=np.concatenate((h,i),axis=0)
j

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
k=np.concatenate((h,i),axis=1)
k

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [98]:
l=np.array([1,2,3,4,5,6])
np.split(l,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [99]:
np.split(l,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [100]:
e[:4]

array([12, 60, 70, 80])

In [106]:
m=np.array([[1,2,3,4,5],[6,7,8,9,10]])
m[:1,:1]

array([[1]])

In [107]:
m[:2,1]

array([2, 7])

In [109]:
n=np.array([[1,2,3],[4,5,6]])
p=np.array([[4,5,6],[7,8,9]])

In [110]:
np.add(n,p)

array([[ 5,  7,  9],
       [11, 13, 15]])

In [111]:
np.subtract(n,p)

array([[-3, -3, -3],
       [-3, -3, -3]])

In [112]:
np.multiply(n,p)

array([[ 4, 10, 18],
       [28, 40, 54]])

In [113]:
np.divide(n,p)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667]])

In [115]:
np.exp(n)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [116]:
np.sqrt(n)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [117]:
n.max()

6

In [120]:
n.min()

1

In [121]:
n.sum()

21

In [122]:
n.mean()

3.5

In [125]:
q=np.median(n)
q

3.5