In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("iris.csv")
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
#
df['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [5]:
# y= labeldata
y= df.iloc[:,4].values

In [15]:
x=df.iloc[:,0:4].values


In [7]:
# x= features
x


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [9]:
#conver y in number encoding
from sklearn.preprocessing import LabelEncoder

In [10]:
labelencoder_y= LabelEncoder()

In [11]:
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from sklearn.model_selection import train_test_split 
#use for 20% or 80% train nd test data

In [18]:
#  x= x_train,x_test,y=y_test,y_train
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3) 

In [19]:
x_test

array([[5.9, 3. , 4.2, 1.5],
       [5.7, 2.5, 5. , 2. ],
       [6.4, 2.8, 5.6, 2.1],
       [6.6, 3. , 4.4, 1.4],
       [6.3, 2.9, 5.6, 1.8],
       [4.8, 3. , 1.4, 0.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.5, 2.3, 4. , 1.3],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [5. , 3.5, 1.3, 0.3],
       [6. , 2.2, 4. , 1. ],
       [5.2, 3.5, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.2, 4.5, 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [4.8, 3.4, 1.6, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [6.5, 3. , 5.8, 2.2],
       [5.7, 3. , 4.2, 1.2],
       [6.9, 3.1, 5.4, 2.1],
       [5.6, 2.8, 4.9, 2. ],
       [6.8, 3. , 5.5, 2.1],
       [5.6, 3. , 4.1, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.1, 5.6, 2.4],
       [4.8, 3.4, 1.9, 0.2],
       [7.2, 3

In [20]:
x_train

array([[5.1, 3.7, 1.5, 0.4],
       [5.9, 3. , 5.1, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [5.6, 2.5, 3.9, 1.1],
       [6.9, 3.1, 5.1, 2.3],
       [5.4, 3. , 4.5, 1.5],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 4.1, 1.5, 0.1],
       [6.5, 3. , 5.2, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [6.5, 2.8, 4.6, 1.5],
       [5.5, 2.4, 3.8, 1.1],
       [5. , 3.2, 1.2, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.1, 3.4, 1.5, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.4, 3.1, 5.5, 1.8],
       [4.9, 2.4, 3.3, 1. ],
       [5.2, 2.7, 3.9, 1.4],
       [6. , 2.9, 4.5, 1.5],
       [6.4, 2.9, 4.3, 1.3],
       [7.4, 2.8, 6.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [6. , 2.7, 5.1, 1.6],
       [4.6, 3

In [21]:
x_train.size

420

In [22]:
x_test.size

180

In [23]:
y_train.size

105

In [24]:
y_test.size

45

In [25]:
#
from sklearn.linear_model import LogisticRegression

In [26]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)
#x_train = 70% nd y_train =30% its show xtrain give the data in output as a ytrain 
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [ ]:
x1=df.iloc [ [1], [0,1,2,3] ] # find the first row in dataset
x1
y_pred= logmodel.predict(x1)
y_pred
#conver encoding to decoding
inverted = labelencoder_y.inverse_transform(y_pred)
inverted


In [ ]:
x1=df.iloc [ [1], [0,1,2,3] ] 
x1
y_pred= logmodel.predict(x1)
y_pred
inverted = labelencoder_y.inverse_transform(y_pred)
inverted
labelencoder_y= LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

In [27]:
x_test

array([[5.9, 3. , 4.2, 1.5],
       [5.7, 2.5, 5. , 2. ],
       [6.4, 2.8, 5.6, 2.1],
       [6.6, 3. , 4.4, 1.4],
       [6.3, 2.9, 5.6, 1.8],
       [4.8, 3. , 1.4, 0.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.5, 2.3, 4. , 1.3],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [5. , 3.5, 1.3, 0.3],
       [6. , 2.2, 4. , 1. ],
       [5.2, 3.5, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.2, 4.5, 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [4.8, 3.4, 1.6, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [6.5, 3. , 5.8, 2.2],
       [5.7, 3. , 4.2, 1.2],
       [6.9, 3.1, 5.4, 2.1],
       [5.6, 2.8, 4.9, 2. ],
       [6.8, 3. , 5.5, 2.1],
       [5.6, 3. , 4.1, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.1, 5.6, 2.4],
       [4.8, 3.4, 1.9, 0.2],
       [7.2, 3

In [28]:
y_pred= logmodel.predict(x_test)
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [29]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0, 14,  0],
       [ 0,  0, 16]], dtype=int64)

In [32]:
logmodel.score(x_test,y_test)

1.0

In [1]:
classifier_svc_sig.score(x_test,y_test)

NameError: name 'classifier_svc_sig' is not defined

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
classifier_Knn = KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)

In [35]:
classifier_Knn

KNeighborsClassifier()

In [36]:
classifier_Knn.fit(x_train,y_train)

KNeighborsClassifier()

In [37]:
y_pred_knn = classifier_Knn.predict(x_test)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [38]:
y_pred_knn

array([1, 2, 2, 1, 2, 0, 1, 1, 0, 2, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 0, 2,
       0, 2, 1, 2, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2, 1,
       1])

In [39]:
confusion_matrix(y_test,y_pred_knn)

array([[15,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 16]], dtype=int64)

In [40]:
classifier_Knn.score(x_test,y_test)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9777777777777777

In [41]:
from sklearn.naive_bayes import GaussianNB

In [42]:
classifier_nb = GaussianNB()

In [43]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [44]:
y_pred = classifier_nb.predict(x_test)

In [45]:
y_pred

array([1, 2, 2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 0, 1,
       0, 2, 1, 2, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2, 1,
       1])

In [46]:
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [47]:
classifier_nb.score(x_test,y_test)

0.9777777777777777

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
accuracy_score(y_pred,y_test)

0.9777777777777777

In [50]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0, 14,  0],
       [ 0,  1, 15]], dtype=int64)

In [51]:
from sklearn.svm import SVC

In [52]:
classifier_svc_sig = SVC(kernel = 'sigmoid') #rbf ,linear,poly

In [53]:
classifier_svc_sig

SVC(kernel='sigmoid')

In [54]:
classifier_svc_sig.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [55]:
y_pred_svc = classifier_svc_sig.predict(x_test)

In [56]:
y_pred_svc

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [57]:
y_test

array([1, 2, 2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 0, 2,
       0, 2, 1, 2, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2, 1,
       1])

In [58]:
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [59]:
confusion_matrix(y_test,y_pred_svc)

array([[ 0, 15,  0],
       [ 0, 14,  0],
       [ 0, 16,  0]], dtype=int64)

In [60]:
classifier_svc_sig.score(x_test,y_test)

0.3111111111111111